config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'

  get '/login',    to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  post '/sessions/create', to: 'sessions#create', as: 'session'

  get '/register', to: 'users#new', as: 'new_user'

  resources :users, except: [:new, :destroy]
  resources :posts, except: [:index]
  resources :comments, except: [:index, :edit, :update]
  resources :follows, except: [:index, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :content
	belongs_to :user, class_name: 'User', foreign_key: 'user_id'
	belongs_to :post, class_name: 'Post', foreign_key: 'post_id'
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User', foreign_key: 'user_id'
  belongs_to :target, class_name: 'User', foreign_key: 'target_id'
end

app/models/post.rb
class Post < ApplicationRecord
	validates_presence_of :title, :content
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_many :posts

  has_many :active_relationships, class_name: 'Follow', foreign_key: 'user_id'
  has_many :following, through: :active_relationships,  source: :target

  has_many :passive_relationships, class_name: 'Follow', foreign_key: 'target_id'
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(user)
    active_relationships.create(target_id: user.id)
  end

  def unfollow(user)
     active_relationships.find_by(target_id: user.id).destroy
  end

  def following?(user)
    following.include?(user)
  end

  def get_follow(user)
    Follow.where(user_id: self.id, target_id: user.id).first
  end

  def feed
    following_ids = "SELECT target_id FROM follows WHERE user_id = :user_id"
    Post.where("user_id IN (#{following_ids}) OR user_id = :user_id", user_id: id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include ApplicationHelper

  protect_from_forgery with: :exception

  protected

    def not_found
      raise ActionController::RoutingError.new('Not Found')
    end

    def confirm_logged_in
      unless current_user
        flash[:notice] = 'Please log in!'
        redirect_to(login_path)
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # GET /comments
  def index
    @comments = Comment.all
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id

    if !@comment.save
      @post = @comment.post
      render('posts/show')
    else
      flash[:notice] = "Comment successfully created!"
      redirect_to :back
    end
  end

  def new
  end

  def destroy
    Comment.find(params[:id]).destroy
    flash[:notice] = "Comment successfully deleted!"
    redirect_to("/posts")
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :post_id)
    end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  def create
    target = User.find(params[:target_id])

    if target.nil?
      not_found
    else
      if false == current_user.following?(target)
        flash[:notice] = "You are now following #{target.name}!"
        Follow.create(user_id: current_user.id, target_id: params[:target_id])
      end
      redirect_to :back
    end
  end

  def new
    @follow = Follow.new
  end

  def show
    @follow = Follow.find(params[:id])
  end

  def destroy
    follow = Follow.find(params[:id])
    flash[:notice] = "You unfollowed #{follow.target.name}!"
    follow.destroy
    redirect_to :back
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		@posts = current_user ? current_user.feed : Post.all
		render('home')
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :confirm_logged_in
  before_action :confirm_post_owner, except: [:new, :create, :show]

  def create
    @post = Post.new(post_params)

    @post.user_id = current_user.id

    if @post.save
      flash[:notice] = "Post successfully created!"
      redirect_to(post_path(@post.id))
    else
      render('new')
    end
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def show
    @comment = Comment.new
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post successfully updated!"
      redirect_to(post_path(@post.id))
    else
      render("edit")
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = "Post successfully deleted!"
    redirect_to("/posts")
  end

  private
    def post_params
      params.require(:post).permit(:title, :content)
    end

    def set_post
      @post = Post.find(params[:id])
    end

    def confirm_post_owner
      unless current_user && current_user.id == @post.user.id
        not_found
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = params[:user]
  	@user = User.where(email: user[:email]).first
  	if @user && @user.password == user[:password]
  		session[:user_id] = @user.id
  		flash[:notice] = "You are logged in!"
			redirect_to root_path
  	else
  		flash[:notice] = "Bad credentials"
  		redirect_to login_path
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :confirm_logged_in, only: [:index, :update, :edit, :show]

  def index
    @users = User.all
  end

  def create
  	@user = User.new(user_params)

    if @user.save
      flash[:notice] = "User successfully created!"
      redirect_to(new_post_path)
    else
      render("new")
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = "User successfully updated!"
      redirect_to("/users")
    else
      render("edit")
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :name, :password, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_user
		User.where(id: session[:user_id]).first
	end
end

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
    <% if comment.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
            <ul>
                <% comment.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="field">
        <%= f.text_area :content, size: "60x3" %>
    </div>
    <input type="hidden" name="comment[post_id]" value="<%= @post.id %>">
    <%= f.submit %>
<% end %>

app/views/comments/_show.html.erb
<div class="comment">
    <p><%= comment.content %></p>
    <span class="author"><a href="<%= user_path(comment.user.id) %>"><%= comment.user.name %></a></span>
    <span class="time"><%= time_ago_in_words(comment.created_at) %> ago </span>
</div> <!-- .comment -->

app/views/follows/new.html.erb
<h1>New</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>Z-M-C Bloggin' on Rails</title>
</head>
<body>
    <nav>
        <% if current_user %>
            <div class="avatar">
                <a href="<%= user_path(current_user.id) %>">
                    <%= image_tag current_user.avatar.url(:thumb) %>
                </a>
            </div>
            <div class="items">
                <a class="first" href="<%= root_path %>">Home</a>
                <a href="<%= new_post_path %>">New Post</a>
                <a href="<%= logout_path %>">Sign Out </a>
            </div>
        <% else %>
            <div class="items">
                <a href="<%= new_user_path %>">Join Us</a>
                <a href="<%= login_path %>">Log In</a>
            </div>
        <% end %>
    </nav>

    <div id="main">
        <div class="container">
            <% if flash[:notice] %>
                <%= flash[:notice] %>
            <% end %>
            <%= yield %>
        </div>
    </div>

    <div id="site-footer">
        <div class="container">
            <p>Special Rails Blog by NYCDA-AUSTIN JANUARY 17</p>
        </div>
        <div id="bottomstrip">Come back and see us!</div>
    </div>
</body>
</html>

app/views/pages/home.html.erb
<% if current_user %>
    <div class="following">
        <% current_user.following.each do |person| %>
            <!-- use person to fill in properties -->
            <!-- show the image of people current_user is following -->
        <% end %>
    </div>
<% end %>


<div>
    <% @posts.each do |p| %>
        <div class="post">
            <h4>
                <a href="<%= user_path(p.user.id) %>">
                    <div class="avatar">
                        <%= image_tag p.user.avatar.url(:thumb) %>
                    </div>
                </a>
            </h4>
            <h2 class="post-title">
                <a href="<%= post_path(p.id) %>">
                    <%= p.title %>
                </a>
            </h2>
            <div class="post-body">
                <%= p.content %>
            </div> <!-- .post-body -->
            <div class="post-meta">
                <a class="author" href="<%= user_path(p.user.id) %>"><%= p.user.name %></a>
                <br />
                published <%= time_ago_in_words(p.created_at) %>
            </div> <!-- .post-meta -->
        </div>
    <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
    <% if post.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
            <ul>
                <% post.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>

    <div class="field">
        <%= f.label :content %>
        <%= f.text_area :content, size: "60x12" %>
    </div>

    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post: <%= @post.title %></h1>
<%= render('form', post: @post) %>

app/views/posts/index.html.erb
<% @posts.each do |p| %>
    <div class="post">
        <h1><a href="<%= post_path(p.id) %>"><%= p.title %></a></h1>
    </div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render('form', post: @post) %>

app/views/posts/show.html.erb
<h1 class="post-title"><%= @post.title %></h1>
<div class="post-meta">
    <span class="author"><a href="<%= user_path(@post.user.id) %>"><%= @post.user.name %></a></span>
    <span class="published"><b>Published:</b> <%= time_ago_in_words(@post.created_at) %></span>
</div> <!-- .post-meta -->

<div class="post-body">
	<%= @post.content %>
</div> <!-- .post-body -->

<h4>Insert rude comment here:</h4>
<%= render('comments/form', comment: @comment) %>

<% @post.comments.each do |c| %>
    <%= render('comments/show', comment: c) %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(user, html: { multipart: true })  do |f| %>
    <% if user.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
            <ul>
                <% user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= f.file_field :avatar %>

    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div>

    <div class="field">
        <%= f.label :password %>
        <%= f.text_field :password %>
    </div>

    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

<%= form_for @user, method: :delete do |f| %>
    <%= f.submit "Delete" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User: <%= @user.name %></h1>
<%= render('form', user: @user) %>

app/views/users/join.html.erb
<h1>Register-Join</h1>

<form action="/users" method="POST">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
    <label>User ID</label>
    <input type="text" name="user[username]">
    <br />

    <label>Email</label>
    <input type="text" name="user[email]">
    <br />

      <label>Password</label>
    <input type="text" name="user[password]">
    <br />
    <input type="submit">
</form>
<br />
<a href="/users">Users Index</a>

app/views/users/login.html.erb
<h1>Login</h1>

<form action="/sessions/create" method="POST">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />

    <label>Email</label>
    <input type="text" name="user[email]">
    <br />
    <label>Password</label>
    <input type="password" name="user[password]">
    <br />
    <input type="submit">
</form>
<br />
<a href="/users">Users Index</a>

app/views/users/new.html.erb
<h1>Register</h1>

<%= render('form', user: @user) %>

app/views/users/show.html.erb
<div class="avatar-big">
    <a href="<%= user_path(current_user.id) %>">
        <%= image_tag current_user.avatar.url(:medium) %>
    </a>
</div>
<div class="user-details">
    <h1><%= @user.name %></h1>
    <div><%= @user.email %></div>

    <% if current_user.id == @user.id %>
    	<a href="<%= edit_user_path %>">Edit Profile</a>
    <% end %>

    <% if current_user && !current_user.following?(@user) %>
        <form action="<%= follows_path %>" method="POST">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
            <input type="hidden" name="target_id" value="<%= @user.id %>" />
            <input type="submit" value="Follow" />
        </form>
    <% else %>
        <form action="<%= follow_path(current_user.get_follow(@user).id) %>" method="POST">
            <input type="hidden" name="_method" value="DELETE" />
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
            <input type="submit" value="Unfollow" />
        </form>
    <% end %>
</div>

<div class="user-posts">
    <% @user.posts.each do |p| %>
        <div class="post user-post">
            <h4>
                <a href="<%= user_path(p.user.id) %>">
                    <div class="avatar">
                        <%= image_tag p.user.avatar.url(:thumb) %>
                    </div>
                </a>
            </h4>
            <h2 class="post-title">
                <a href="<%= post_path(p.id) %>">
                    <%= p.title %>
                </a>
            </h2>
            <div class="post-body"><%= p.content %></div>
            <div class="post-meta">
            	<span class="author"><a href="<%= user_path(p.user.id) %>"><%= p.user.name %></a></span>
				<span class="published">published <%= time_ago_in_words(p.created_at) %> ago</span>
            </div>
        </div>
    <% end %>
</div>